#15 Few Resources added [Kotlin] [UI/UX]
facebook-developer-circle-delhi/Community-Curated-Resources pull request #21
Opened 2018-07-30 09:14 UTC by SparshWadhwa

Resources added to start with Kotlin Language and some awesome libraries for Polishing UI.

2018-07-30 15:45 UTC, saranshkataria commented
We should probably add the header for Java too if we are adding for Kotlin. Also the description does not make any sense in there. And making a section for UI/UX is overkill in my opinion
@harshitjuneja thoughts?

2018-07-31 17:41 UTC, harshitjuneja requested changes
1. remove description
2. Don't need UI/UX in this file.

2018-07-31 17:41 UTC, harshitjuneja commented on Android.md
> +Kotlin is a statically typed programming language that runs on the Java virtual machine and also can be compiled to JavaScript source code or use the LLVM compiler infrastructure.
Remove the description. Not needed.

2018-07-31 17:41 UTC, harshitjuneja commented on Android.md
> +1.  [A curated list of awesome Android UI/UX libraries ](https://github.com/wasabeef/awesome-android-ui) #AwesomeUI.
UI/UX in here isn't relevant. Raise a different pull request for UI resources so that we have a separate file for those.

2018-08-02 06:24 UTC, SparshWadhwa commented on Android.md
> +1.  [A curated list of awesome Android UI/UX libraries ](https://github.com/wasabeef/awesome-android-ui) #AwesomeUI.
But do you feel is there any need of separate file in this repo containing links for some app components libraries @harshitjuneja

2018-10-29 07:48 UTC, saranshkataria commented
Closing out due to inactivity

2018-10-29 07:48 UTC, closed without merging